# Generated by Django 3.2.7 on 2021-09-09 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_rename_title_plog_header'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plog',
            old_name='body',
            new_name='note',
        ),
    ]
